qna/models.py
from datetime import datetime

from bs4 import BeautifulSoup
from flask import current_app
from flask_login import UserMixin, AnonymousUserMixin
from jieba.analyse import ChineseAnalyzer
from markdown import markdown
from werkzeug.security import generate_password_hash, check_password_hash

from . import db, login_manager


class Permission:
    """FOLLOW：表示是否能够关注其它用户的权限
    COMMENT：表示是否能够发表评论的权限
    WRITE_ARTICLES：表示是否能够写文章的权限
    MODERATE_COMMENTS：表示是否能够管理评论的权限
    ADMINISTER：表示是否能够管理网站的权限"""
    FOLLOW = 0x01
    COMMENT = 0x02
    WRITE_ARTICLES = 0x04
    MODERATE_COMMENTS = 0x08
    ADMINISTER = 0x80


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    default = db.Column(db.Boolean, default=False, index=True)
    permissions = db.Column(db.Integer)
    users = db.relationship('User', backref='role', lazy='dynamic')

    @staticmethod
    def insert_roles():
        roles = {
            'User': (Permission.FOLLOW |
                     Permission.COMMENT |
                     Permission.WRITE_ARTICLES, True),
            'Moderator': (Permission.FOLLOW |
                          Permission.COMMENT |
                          Permission.WRITE_ARTICLES |
                          Permission.MODERATE_COMMENTS, False),
            'Administrator': (0xff, False)
        }

        for r in roles:
            role = Role.query.filter_by(name=r).first()
            if role is None:
                role = Role(name=r)
            role.permissions = roles[r][0]
            role.default = roles[r][1]
            db.session.add(role)
        db.session.commit()

    def __repr__(self):
        return '<Role %r>' % self.name

    def __str__(self):
        return '%s' % self.name


class Follow(db.Model):
    __tablename__ = 'follows'
    follower_id = db.Column(db.Integer, db.ForeignKey('users.id'),
                            primary_key=True)
    followed_id = db.Column(db.Integer, db.ForeignKey('users.id'),
                            primary_key=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(64), unique=True)
    email = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    questions = db.relationship('Question', backref='author', lazy='dynamic')
    answers = db.relationship('Answer', backref='author', lazy='dynamic')
    question_comments = db.relationship('QuestionComment', backref='author',
                                        lazy='dynamic')
    answer_comments = db.relationship('AnswerComment', backref='author',
                                      lazy='dynamic')
    followed = db.relationship('Follow',
                               foreign_keys=[Follow.follower_id],
                               backref=db.backref('follower', lazy='joined'),
                               lazy='dynamic',
                               cascade='all, delete-orphan')
    followers = db.relationship('Follow',
                                foreign_keys=[Follow.followed_id],
                                backref=db.backref('followed', lazy='joined'),
                                lazy='dynamic',
                                cascade='all, delete-orphan')

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        if self.role is None:
            if self.email == current_app.config['ADMIN_EMAIL']:
                self.role = Role.query.filter_by(permissions=0xff).first()
            if self.role is None:
                self.role = Role.query.filter_by(default=False).first()

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    # 设置密码散列值
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    # 使用密码和密码散列值进行验证
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def can(self, permissions):
        return self.role is not None and \
               (self.permissions & permissions) == permissions

    def is_administrator(self):
        return self.can(Permission.ADMINISTER)

    def follow(self, user):
        if not self.is_following(user):
            f = Follow(followed=user)
            self.followed.append(f)

    def unfollow(self, user):
        f = self.followed.filter_by(followed_id=user.id).first()
        if f:
            self.followed.remove(f)

    def is_following(self, user):
        return self.followed.filter_by(
            followed_id=user.id).first() is not None

    def is_followed_by(self, user):
        return self.followers.filter_by(
            follower_id=user.id).first() is not None

    def __str__(self):
        return '%s' % self.fullname

    def __repr__(self):
        return '<User %r>' % self.fullname


class AnonymousUser(AnonymousUserMixin):
    def can(self, permissions):
        return False

    def is_administrator(self):
        return False


login_manager.anonymous_user = AnonymousUser


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


topic_question_table = db.Table('topic_question_table',
                                db.Column('topic_id',
                                          db.Integer,
                                          db.ForeignKey('topics.id')),
                                db.Column('question_id',
                                          db.Integer,
                                          db.ForeignKey('questions.id')))


class Topic(db.Model):
    __tablename__ = 'topics'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    description = db.Column(db.Text)
    questions = db.relationship('Question', secondary=topic_question_table,
                                backref=db.backref('topics', lazy='dynamic'),
                                lazy='dynamic')

    def __repr__(self):
        return '<Topic %r>' % self.name

    def __str__(self):
        return '%s' % self.name


class Question(db.Model):
    __tablename__ = 'questions'
    __searchable__ = ['title', 'description']
    __analyzer__ = ChineseAnalyzer()
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.Text)
    description = db.Column(db.Text)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    comments = db.relationship('QuestionComment', backref='question',
                               lazy='dynamic')
    answers = db.relationship('Answer', backref='question', lazy='dynamic')

    def __repr__(self):
        return '<Question %r>' % self.title

    def __str__(self):
        return '%s' % self.title


class Comment():
    content = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)


class QuestionComment(Comment, db.Model):
    __tablename__ = 'question_comments'
    id = db.Column(db.Integer, primary_key=True)
    question_id = db.Column(db.Integer, db.ForeignKey('questions.id'))
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))


class Answer(db.Model):
    __tablename__ = 'answers'
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text)
    content_html = db.Column(db.Text)
    summary = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    question_id = db.Column(db.Integer, db.ForeignKey('questions.id'))
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comments = db.relationship('AnswerComment', backref='answer',
                               lazy='dynamic')
    summary_img_url = db.Column(db.Text)

    @staticmethod
    def content_changed(target, value, oldvalue, initiator):
        extensions = ['markdown.extensions.extra',
                      'markdown.extensions.fenced_code',
                      'markdown.extensions.footnotes',
                      'markdown.extensions.tables',
                      'markdown.extensions.codehilite',
                      'markdown.extensions.wikilinks',
                      ]
        target.content_html = markdown(value,
                                       extensions=extensions,
                                       output_format='html')
        lines = value.split('\n')
        summary_text = '\n'.join(lines[:5])
        target.summary = markdown(summary_text,
                                  extensions=extensions,
                                  output_format='html')
        soup = BeautifulSoup(target.content_html, 'html.parser')
        if soup.find('img') is not None:
            target.summary_img_url = soup.find('img')['src']


db.event.listen(Answer.content, 'set', Answer.content_changed)


class AnswerComment(Comment, db.Model):
    __tablename__ = 'answer_comments'
    id = db.Column(db.Integer, primary_key=True)
    answer_id = db.Column(db.Integer, db.ForeignKey('answers.id'))
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))

qna/__init__.py
import flask_whooshalchemyplus
from flask import Flask
from flask_admin import Admin
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

from config import config

db = SQLAlchemy()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
ad = Admin(name='知乎后台', template_mode='bootstrap3')


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)
    ad.init_app(app)
    flask_whooshalchemyplus.init_app(app)

    from .views import site
    app.register_blueprint(site)

    return app

qna/views.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from flask_login import current_user, login_required, login_user, logout_user

from . import db
from .models import Question, Answer, User

site = Blueprint('site', __name__)


@site.route('/', methods=['GET', 'POST'])
def home():
    # if not current_user.is_authenticated:
    #     return render_template('auth/signup.html')
    questions = Question.query.all()
    return render_template('home.html', questions=questions)


@site.route('/explore')
def explore():
    return render_template('explore.html')


@site.route('/ask', methods=['GET', 'POST'])
@login_required
def ask_question():
    if current_user.is_authenticated and request.method == 'POST':
        question = Question(title=request.form.get("title"),
                            description=request.form.get("content"),
                            author=current_user._get_current_object())
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('.question', id=question.id))
    elif not current_user.is_authenticated:
        return redirect(url_for('site.signin'))


@site.route('/question/<int:id>', methods=['GET', 'POST'])
def question(id):
    question = Question.query.get_or_404(id)
    if request.method == 'POST':
        answer = Answer(content=request.form['answer'],
                        question=question,
                        author=current_user._get_current_object())
        db.session.add(answer)
        db.session.commit()
        return redirect(url_for('.question', id=question.id))
    answers = question.answers.order_by(Answer.timestamp.asc()).all()
    return render_template('question.html', question=question, answers=answers)


@site.route('/search', methods=['GET', 'POST'])
def search():
    if request.method == 'POST':
        key_word = request.form.get('q')
        print(key_word)
        results = Question.query.whoosh_search(key_word)
        return render_template('search.html', key_word=key_word,
                               results=results)


@site.route('/signin', methods=['GET', 'POST'])
def signin():
    if current_user.is_authenticated:
        return redirect(url_for('site.home'))
    if request.method == 'POST':
        user = User.query.filter_by(email=request.form.get('account')).first()
        if user is not None and user.verify_password(request.form.get('password')):
            login_user(user, remember=True)
            return redirect(request.args.get('next') or url_for('site.home'))
    return render_template('auth/signin.html')


@site.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))


@site.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        user = User(email=request.form.get("email"),
                    fullname=request.form.get("fullname"),
                    password=request.form.get("password"))
        print(user.email, user.fullname, request.form.get("password"))
        print(request.form.get("email"))
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('site.signin'))
    return render_template('auth/signup.html')


@site.app_errorhandler(404)
def page_not_found(e):
    if request.accept_mimetypes.accept_json and \
            not request.accept_mimetypes.accept_html:
        response = jsonify({'error': 'not found'})
        response.status_code = 404
        return response
    return render_template('404.html'), 404

qna/templates/_answer_add.html
<div class="Card QuestionAnswers-answerAdd">
	<div class="AnswerAdd">
		<div class="AnswerAdd-header">
			<div class="AuthorInfo AnswerAdd-info">
				<span class="UserLink AuthorInfo-avatarWrapper"><img class="Avatar AuthorInfo-avatar" width="38" height="38" src="https://pic1.zhimg.com/da8e974dc_xs.jpg" srcset="https://pic1.zhimg.com/da8e974dc_l.jpg 2x" alt="用户名"></span>
				<div class="AuthorInfo-content">
					<div class="AuthorInfo-head"><span class="UserLink AuthorInfo-name">用户名</span></div>
					<div class="AuthorInfo-detail">
						<div class="AuthorInfo-badge">
							<button class="Button ModifyButton AnswerAdd-topicBiosButton Button--link" type="button">
								<svg viewBox="0 0 12 12" class="Icon ModifyButton-icon Icon--modify" width="12" height="16" aria-hidden="true" style="height: 16px; width: 12px;"><title></title><g><path d="M.423 10.32L0 12l1.667-.474 1.55-.44-2.4-2.33-.394 1.564zM10.153.233c-.327-.318-.85-.31-1.17.018l-.793.817 2.49 2.414.792-.814c.318-.328.312-.852-.017-1.17l-1.3-1.263zM3.84 10.536L1.35 8.122l6.265-6.46 2.49 2.414-6.265 6.46z" fill-rule="evenodd"></path></g></svg>编辑话题经验
							</button>
						</div>
					</div>
				</div>
			</div>
			<button class="Button AnswerAdd-toggleAnonymous Button--plain" type="button">使用匿名身份回答</button>
		</div>

		<form class="AnswerForm" method="POST" action="{{ url_for('site.question', id=question.id) }}">
			<textarea id="answer-editor" name="answer"></textarea>
			<div>
				<div class="Sticky AnswerForm-footer is-bottom" style="width: 692px; bottom: 0px; left: 132.5px;">
					<div class="AnswerForm-status"></div>
					<div class="AnswerForm-footerRight">
						<div class="Popover">
							<button class="Button Select-button Select-plainButton Button--plain" role="combobox" aria-expanded="false" type="button" id="Popover-40404-81802-toggle" aria-haspopup="true" aria-owns="Popover-40404-81802-content">允许规范转载<svg viewBox="0 0 8 13" class="Icon Select-arrow Icon--select" width="8" height="16" aria-hidden="true" style="height: 16px; width: 8px;"><title></title><g><path d="M4 11.183L1.284 8.218c-.293-.29-.77-.29-1.064 0-.293.29-.293.76 0 1.052l3.25 3.512c.292.29.768.29 1.062 0L7.78 9.27c.293-.29.293-.76 0-1.052-.295-.29-.77-.29-1.064 0L4 11.182zM4 1.818L1.284 4.782c-.293.29-.77.29-1.064 0-.293-.29-.293-.76 0-1.052L3.47.218c.292-.29.768-.29 1.062 0L7.78 3.73c.293.29.293.76 0 1.052-.295.29-.77.29-1.064 0L4 1.82z"></path></g></svg></button>
						</div>
						<button class="Button AnswerForm-submit Button--primary Button--blue" type="submit">提交回答</button>
					</div>
				</div>
			</div>
		</form>
	</div>
</div>

qna/templates/_ask_modal.html
<div class="modal" id="askModal" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h1 class="modal-title-text">提问</h1>
			</div>
			<div class="modal-body">
				<form class="add-question-form" method="POST" action="{{ url_for('site.ask_question') }}">
					<div class="question-title">
		      			<textarea class="form-control" rows="1" placeholder="写下你的问题" name="title"></textarea>
		      		</div>
		        	<div class="question-content">
		        		<span class="content-head">问题说明（可选）：</span>
		        		<textarea class="form-control" rows="3" placeholder="问题背景、条件等详细信息" name="content"></textarea>
		        	</div>
		        	<div class="question-footer">
		        		<span class="footer-head">选择话题：</span>
		        		<input type="text" class="form-control" placeholder="暂不可用" disabled="">
		        	</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
				<button type="button" class="btn btn-primary submit">发布</button>
			</div>
		</div>
	</div>
</div>

qna/templates/_home_feed_item.html
<div class="feed-item folding feed-item-hook feed-item-0" feed-item-a="" data-type="a" id="feed-0" data-za-module="FeedItem" data-za-index="">
	<div class="feed-item-inner">
		<div class="avatar">
			<a title="互联网" data-hovercard="t$t$19550517" class="zm-item-link-avatar" href="" target="_blank"><img src="https://pic4.zhimg.com/f07808da5625fef3607f8b75b770349f_m.jpg" class="side-topic-avatar"></a>
		</div>
		<div class="feed-main">
			<div class="feed-source" data-za-module="FeedSource">
			来自话题: <a href="" data-hovercard="t$b$19550517" data-token="19550517" data-topicid="99" data-follow="1" data-interest="1" target="_blank" data-za-element-name="Title">互联网</a>
			</div>
			<div class="feed-content" data-za-module="AnswerItem">
				<meta itemprop="answer-id" content="60928324">
				<meta itemprop="answer-url-token" content="169723764">
				<h2 class="feed-title"><a class="question_link" href="{{ url_for('site.question', id=q.id) }}" target="_blank" data-id="4280818" data-za-element-name="Title">{{ q.title }}</a></h2>
				<div class="expandable entry-body">
					<link itemprop="url" href="">
					<div class="zm-item-vote">
						<a class="zm-item-vote-count js-expand js-vote-count" href="javascript:;" data-bind-votecount="">0</a>
					</div>

					<div class="zm-votebar" data-za-module="VoteBar">
						<button class="up" aria-pressed="false" title="赞同">
							<i class="icon vote-arrow"></i>
							<span class="count">0</span>
							<span class="label sr-only">赞同</span>
						</button>
						<button class="down" aria-pressed="false" title="反对，不会显示你的姓名">
							<i class="icon vote-arrow"></i>
							<span class="label sr-only">反对，不会显示你的姓名</span>
						</button>
					</div>
					<div class="zm-item-answer-author-info">
						<span class="summary-wrapper">
							<span class="author-link-line">
							<a class="author-link" data-hovercard="p$t$ying-xiong-lian-meng-56-33" target="_blank" href="">{% if q.answers.count() %}{{  q.answers[0].author.fullname }}{% endif %}</a></span><span title="用户签名" class="bio">
							用户签名</span>
						</span>
					</div>

					<div class="zm-item-vote-info" data-votecount="0" data-za-module="VoteInfo">
						<span class="answer-tag">
							<span class="text">收录于 </span>
							<a class="text" data-tooltip="s$t$电竞风云 · 德玛西亚之力" href="/roundtable/lol">知乎圆桌</a>
							<span class="text">、</span>
							<span class="text">编辑推荐</span>
						</span>

						<span class="zg-bull text">•</span><span class="voters text"><a href="#" class="more text"><span class="js-voteCount">0</span>&nbsp;人赞同</a></span>
					</div>
					<div class="zm-item-rich-text expandable js-collapse-body" data-resourceid="4280818" data-action="/answer/content" data-author-name="英雄联盟" data-entry-url="/question/30246012/answer/169723764">

						<textarea hidden="" class="content">{% if q.answers.count() %}{{  q.answers[0].content_html }}{% endif %}</textarea>

						<div class="zh-summary summary clearfix">
							{% if q.answers.count() %}
								{% if q.answers[0].summary_img_url %}
								<img src="{{ q.answers[0].summary_img_url }}" class="origin_image inline-img zh-lightbox-thumb">
								{% else %}
								<!-- <img src="https://pic1.zhimg.com/v2-b6bc7da521ae6cc1b82d9e20edba2bcc_200x112.png" data-rawwidth="589" data-rawheight="348" class="origin_image inline-img zh-lightbox-thumb" data-original="https://pic1.zhimg.com/v2-b6bc7da521ae6cc1b82d9e20edba2bcc_r.png"> -->
								{% endif %}
							{{  q.answers[0].content_html | striptags | truncate(160) }}
							{% endif %}
							<a href="" class="toggle-expand">显示全部</a>
						</div>
						<p class="visible-expanded"><a itemprop="url" class="answer-date-link meta-item" target="_blank" href="">发布于 2017-05-15</a></p>
					</div>
				</div>
				<div class="feed-meta">
					<div class="zm-item-meta answer-actions clearfix js-contentActions">
						<div class="zm-meta-panel">
							<a data-follow="q:link" class="follow-link zg-follow meta-item" href="javascript:;" id="sfb-4280818"><i class="z-icon-follow"></i>关注问题</a>
							<a href="#" name="addcomment" class="meta-item toggle-comment js-toggleCommentBox">
							<i class="z-icon-comment"></i>{{ q.comments.count() }} 条评论</a>
							<a href="#" class="meta-item zu-autohide js-thank" data-thanked="false"><i class="z-icon-thank"></i>感谢</a>

							<a href="#" class="meta-item zu-autohide js-collect"><i class="z-icon-collect"></i>收藏</a>
							<span class="zg-bull zu-autohide">•</span>
							<a href="#" class="meta-item zu-autohide js-noHelp">没有帮助</a>
							<span class="zg-bull zu-autohide">•</span>
							<a href="#" class="meta-item zu-autohide js-report">举报</a>
							<meta name="copyrightStatus" content="0">
							<meta name="disableCopyAvatar" content="https://pic2.zhimg.com/v2-123b568cebf23455ee3231de0f473899_s.jpg">

							<span class="zg-bull">•</span>
							<a href="/terms#sec-licence-6" target="_blank" class="meta-item copyright">禁止转载</a>
							<button class="meta-item item-collapse js-collapse"><i class="z-icon-fold"></i>收起</button>
						</div>
					</div>
					<a href="#" class="ignore zu-autohide" name="dislike" data-tooltip="s$b$不感兴趣"></a>
				</div>
			</div>
		</div>
	</div>
	<div class="undo-dislike-options" data-item_id="0">
		此内容将不会在动态中再次显示 <span class="zg-bull">•</span> <a href="#" class="meta-item revert">撤销</a>
		<a href="#" class="ignore zu-autohide close"></a>
	</div>
</div>

qna/templates/search.html
{% extends 'base.html' %}

{% block title %}
{{ key_word }} - 搜索结果 - {{ super() }}
{% endblock %}

{% block head %}
{{ super() }}

{% endblock %}

{% block content %}
<div class="zg-wrap zu-main clearfix" role="main">
	<div class="zu-main-content">
		<div class="zu-main-content-inner">
			<div class="search-tabs">
				<ul class="tab-navs">
					<li class="tab-nav active">
						<a href="">内容</a>
					</li>
					<li class="tab-nav">
						<a href="">用户</a>
					</li>
					<li class="tab-nav">
						<a href="">话题</a>
					</li>
				</ul>
			</div>
			<div class="range-selector">
				<div class="secondary-tabs">
					<span>按相关度排序</span>
					<span class="secondary-tab-divider"></span>
					<a href="">按赞同数排序</a>
				</div>
				<div class="Sorter">
					<span class="lbl">时间不限</span>
					<a class="lbl" href="">一天内</a>
					<a class="lbl" href="">一周内</a>
					<a class="lbl" href="">三个月内</a>
					<i class="zg-icon zg-icon-double-arrow"></i>
				</div>
			</div>
			<ul class="list contents navigable">
				{% for item in results %}
				<li class="item clearfix">
					<div class="title">
						<a target="_blank" href="{{ url_for('site.question', id=item.id) }}" class="js-title-link">
							{#<em>Python</em> 有那么神吗？#}
							{{ item.title }}
						</a>
					</div>
					{% if item.answers.count() != 0 %}
					<div class="content">
						<div class="entry answer">
							<div class="entry-left hidden-phone">
								<a class="zm-item-vote-count hidden-expanded js-expand js-vote-count" data-bind-votecount="">0</a>
							</div>
						</div>
						<div class="entry-body">
							<div class="entry-meta">
								<div class="author-line summary-wrapper">
									<span class="author-link-line">
										<a class="author author-link" href="">
										{{ item.answers[0].author.fullname }}
										</a>
									</span>
									<span class="bio">这里是简介</span>
								</div>
							</div>
							<div class="entry-content js-collapse-body">
								<div class="summary hidden-expanded">
									{{ item.answers[0].content[:300] }}
									<a class="toggle-expand inline" href="javascript:;">显示全部</a>
								</div>
							</div>
							<div class="actions clearfix js-contentActions">
								<a href="javascript:;" class="action-item zg-follow">
									<i class="fa fa-plus"></i>
									关注问题
								</a>
								<a href="javascript:;" class="action-item js-toggleCommentBox">
									<i class="fa fa-comment-o"></i>
									{{ item.answers[0].comments.count() }} 条评论
								</a>
								<a href="javascript:;" target="_blank" class="action-item js-copyright hidden-phone">作者保留权利</a>
							</div>
						</div>
					</div>
					{% else %}
					<div class="content">
						<div class="actions js-contentActions">
							<a href="javascript:;" class="action-item">
								<i class="fa fa-plus"></i>
								关注问题
							</a>
							<span class="zg-bull" style="color: #999;">•</span>
							<a href="javascript:;" class="action-item">0 人关注</a>
							<span class="zg-bull" style="color: #999;">•</span>
							<a href="javascript:;" class="action-item">0 个回答</a>
						</div>
					</div>
					{% endif %}
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
	<div class="zu-main-sidebar">
		<div class="sidebar-content"></div>
	</div>
</div>
{% endblock %}